### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by szabgab** [craigkai/rt-extension-toggletheme#1]
As I see this repository does not have any Continuous Integration configured. Would you be interested in a pull-request enabling GitHub Actions on this repo? See this post for more details: https://perlmaven.com/ci

**Comment by craigkai** [comment]
Hi Gabor,

I am open to the idea of adding some default CI testing but since this extension is an [RT](https://github.com/bestpractical/rt) extension the workflow .yml file would be a little more involved than normal as it would need to setup RT along with the extension.

**Comment by szabgab** [comment]
I can set up a basic CI skeleton, but I don't know how to set up RT for the testing. Will you add that?

**Comment by craigkai** [comment]
I am going to leave it alone for now, in the future we made add some default CI stuff for extensions and I can add that to this extension at that point. Thanks for the offer though!
